// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXBoS80SPAX69IqI_3FWKddwO3K3QXau4',
    appId: '1:11171922951:web:4c4ae1c88ce6548d8a56a2',
    messagingSenderId: '11171922951',
    projectId: 'explore-lesotho',
    authDomain: 'explore-lesotho.firebaseapp.com',
    storageBucket: 'explore-lesotho.appspot.com',
    measurementId: 'G-ZCCM1E25B3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4itUSfJDLCTv74inHYaq43n-m-C0IAI4',
    appId: '1:11171922951:android:bb76d00977f105888a56a2',
    messagingSenderId: '11171922951',
    projectId: 'explore-lesotho',
    storageBucket: 'explore-lesotho.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC06R05iv6qERGNG6nvQMVUAyNOEgPU9Ow',
    appId: '1:11171922951:ios:bbff33a331f6e6b88a56a2',
    messagingSenderId: '11171922951',
    projectId: 'explore-lesotho',
    storageBucket: 'explore-lesotho.appspot.com',
    iosBundleId: 'com.example.exploreLesotho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC06R05iv6qERGNG6nvQMVUAyNOEgPU9Ow',
    appId: '1:11171922951:ios:bbff33a331f6e6b88a56a2',
    messagingSenderId: '11171922951',
    projectId: 'explore-lesotho',
    storageBucket: 'explore-lesotho.appspot.com',
    iosBundleId: 'com.example.exploreLesotho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXBoS80SPAX69IqI_3FWKddwO3K3QXau4',
    appId: '1:11171922951:web:4744a1d11b27e1c98a56a2',
    messagingSenderId: '11171922951',
    projectId: 'explore-lesotho',
    authDomain: 'explore-lesotho.firebaseapp.com',
    storageBucket: 'explore-lesotho.appspot.com',
    measurementId: 'G-M30YWPYJCT',
  );
}
